config/routes.rb
Rails.application.routes.draw do
  resources :histories
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s 
    }, via: [:get, :post]
  end
  resources :tickets
  resources :photos
  resources :hours
  resources :faqs
  resources :attractions
  resources :directions
  resources :waiver
  resources :history
  get 'attractions/index'  
    
  devise_for :users
  resources :users
  get 'simple_pages/home'

  get 'simple_pages/attractions'

  get 'simple_pages/hours'

  get 'simple_pages/directions'

  get 'simple_pages/tickets'

  get 'simple_pages/photos'

  get 'simple_pages/faq'
    
  get 'simple_pages/waiver'
    
  get 'simple_pages/history'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html      
    
  get 'simple_pages/index'

  root 'simple_pages#index'
  #sets homepage for app

  get 'simple_pages/index'
    
  get '/rules-warnings/', to: redirect('/faqs', status: 301)
    
  get '/faq/', to: redirect('/faqs', status: 301)
    
  get '/Haunted-Houses-Near-Me/', to: redirect('/attractions', status: 301)
    
  get '/manor-hill-tavern-haunt-tour/', to: redirect('/attractions', status: 301)
    
  get '/history/', to: redirect('/', status: 301)
    
  get '/directions/', to: redirect('/attractions', status: 301)
   
  get '/manor-hill-tavern-haunt-tour/', to: redirect('/', status: 301)
    
  get '/polarbearplunge/', to: redirect('/', status: 301)

  get '/media/', to: redirect('/photos', status: 301)
    
  get '/fells-point-shuttle/', to: redirect('/directions', status: 301)

 
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
        cannot :read, User
        cannot :create, User
        if user.admin?
            can :manage, all
        end
    end
end

app/models/attraction.rb
class Attraction < ApplicationRecord
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/hour.rb
class Hour < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end
 
  #removed :registerable to prevent randos
  #devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :validatable

app/models/waiver.rb
class Waiver < ApplicationRecord
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  # You must implement the can_edit_phrases? method.
  # Example:
  #
  # def can_edit_phrases?
  #  current_user.is_admin?
  # end
  def can_edit_phrases?
        user_signed_in?
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waiver_helper.rb
module WaiverHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="canonical" href="https://thenevermorehaunt.com" />
        <meta name="description" content="Baltimore Maryland's most unqiue and terrifying haunted house. The scariest haunted house in Baltimore">
        <meta name="author" content="The Nevermore Haunt">
        <meta name="keywords" content="Haunted House, Haunted Houses near me, Things to do, Baltimore, horror, Haunted Houses near me, Baltimore Haunted House, Maryland Haunted House, Haunted House, Scariest haunted house">
        <title>The Nevermore Haunt - Baltimore's Haunted House</title>

        <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>

        
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


        <%= csrf_meta_tags %>

        
        <!-- Google Tag Manager -->
        <% if Rails.env.production? %>
        <script>
        document.addEventListener('turbolinks:load', function(event) {
          var url = event.data.url;  dataLayer.push({
            'event':'pageView',
            'virtualUrl': url
          });
        });(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-5CFWQG4');
        </script>
        <% end %>
        <!-- End Google Tag Manager -->
        
    </head>


    <body>


        <nav class="navbar fixed-top navbar-expand-lg navbar-dark">
            <div class="row drop-nav-row">
                <div class="col-2 col-lg-12">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>


                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav mr-auto">
                            <a onclick="window.location.href = '/';" class="nav-tickets">Home</a>
                            <a onclick="window.location.href = '/attractions';" class="nav-tickets">Attractions</a>
                            <a onclick="window.location.href = '/directions';" class="nav-tickets">Directions</a>
                            <a onclick="window.location.href = '/photos';" class="nav-tickets">Photos</a>
                            <a onclick="window.location.href = '/faq';" class="nav-tickets">FAQ</a>
                            
                            <!--<%= link_to "Home", root_path %>
                            <%= link_to "Attractions", attractions_path %>
                            <%= link_to "Directions", directions_path %>
                            <%= link_to "Photos", photos_path %>    
                            <%= link_to "FAQ", faqs_path %>-->
                            <a onclick="window.location.href = '/tickets';" class="nav-tickets">Tickets</a>

                            <!--<%= link_to "Tickets", tickets_path %>-->


                            <% if user_signed_in? %>
                            <%= link_to('Logout', destroy_user_session_path, method: :delete ) %>
                            <% else %>
                            <!--<%= link_to('Login', new_user_session_path ) %>-->
                            <% end %>


                        </div>
                    </div>
                </div>

                <div class="col-8 col-lg-12 brand-col"><a class="navbar-brand" href="#"><%= image_tag("logo-primary.png", :class => "navbar-logo") %></a></div>

                <div class="col-2 buy-ticket-col" id="floating_button"><button onclick="window.location.href = '/tickets';" class="floating-spooky button-glow">
                    <span class="noth2">Buy Tickets</span>
                    </button></div>

            </div>




        </nav>

 
        <% if notice %>
        <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>

        <footer class="page-footer">
            <div class="text-center">
                <a onclick="window.location.href = '/waiver';">Waiver, Rules &amp; Warnings</a>
                <p>The Nevermore Haunt<br>
                    450 Mott St. <br> Baltimore, MD <br> 410.696.3313 <br> info@thenevermorehaunt.com</p>
            <a href="https://www.facebook.com/thenevermorehaunt/" target="_blank"><i class="fab fa-facebook"></i></a>   <a href="https://twitter.com/nevermorebmore" target="_blank"><i class="fab fa-twitter-square"></i></a>   <a href="https://www.instagram.com/nevermore.baltimore/" target="_blank"><i class="fab fa-instagram"></i></a>
            </div>
            <div class="footer-copyright text-center py-3"><p>© 2019 Engineered Fear Productions, LLC</p>
            </div>     

        </footer>

            <script async defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
           <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=IM+Fell+English&display=swap" rel="stylesheet">
            <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
    </body>




    

</html>