config/routes.rb
Rails.application.routes.draw do
  resources :histories
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s 
    }, via: [:get, :post]
  end
  resources :tickets
  resources :photos
  resources :hours
  resources :faqs
  resources :attractions
  resources :directions
  resources :waiver
  resources :history
  get 'attractions/index'  
    
  devise_for :users
  resources :users
  get 'simple_pages/home'

  get 'simple_pages/attractions'

  get 'simple_pages/hours'

  get 'simple_pages/directions'

  get 'simple_pages/tickets'

  get 'simple_pages/photos'

  get 'simple_pages/faq'
    
  get 'simple_pages/waiver'
    
  get 'simple_pages/history'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html      
    
  get 'simple_pages/index'

  root 'simple_pages#index'
  #sets homepage for app

  get 'simple_pages/index'
    
  get '/rules-warnings/', to: redirect('/faqs', status: 301)
    
  get '/faq/', to: redirect('/faqs', status: 301)
    
  get '/Haunted-Houses-Near-Me/', to: redirect('/attractions', status: 301)
    
  get '/manor-hill-tavern-haunt-tour/', to: redirect('/attractions', status: 301)
    
  get '/history/', to: redirect('/', status: 301)
    
  get '/directions/', to: redirect('/attractions', status: 301)
   
  get '/manor-hill-tavern-haunt-tour/', to: redirect('/', status: 301)
    
  get '/polarbearplunge/', to: redirect('/', status: 301)

  get '/media/', to: redirect('/photos', status: 301)
    
  get '/fells-point-shuttle/', to: redirect('/directions', status: 301)

 
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
        cannot :read, User
        cannot :create, User
        if user.admin?
            can :manage, all
        end
    end
end

app/models/attraction.rb
class Attraction < ApplicationRecord
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/hour.rb
class Hour < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end
 
  #removed :registerable to prevent randos
  #devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :validatable

app/models/waiver.rb
class Waiver < ApplicationRecord
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.fetch(:attraction, {})
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  # You must implement the can_edit_phrases? method.
  # Example:
  #
  # def can_edit_phrases?
  #  current_user.is_admin?
  # end
  def can_edit_phrases?
        user_signed_in?
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waiver_helper.rb
module WaiverHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5CFWQG4"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->

<p id="notice"><%= notice %></p>



<div class="container-fluid sub-page attractions">

    <h1>Attractions</h1>
    <br><br>
    <div class="attractions-about">
        <p><%= phrase('nevermore-general-about') %></p>
    </div>
    <div class="row card-row">
        <div class="col-12 col-md-4 card-col">
            <div class="card-container">
                <h2>The Nevermore Haunt</h2>
                <div class="card">
                    <div class="side"><%= image_tag("patient-attractions.jpg", :class => "card-img") %>
                    </div>
                    <div class="side back"><p><%= phrase('attractions-nevermore-description') %></p></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 card-col">
            <div class="card-container">
                <h2>Isaac's Maleficent Sideshow</h2>
                <div class="card">
                    <div class="side"><%= image_tag("pajama-man-attractions.jpg", :class => "card-img") %></div>
                    <div class="side back"><p><%= phrase('attractions-sideshow-description') %></p></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 card-col">
            <div class="card-container">
                <h2>Food &amp; Drink</h2>
                <div class="card">
                    <div class="side"><%= image_tag("hot-dogs.jpg", :class => "card-img") %></div>
                    <div class="side back"><p><%= phrase('attractions-food-drink-description') %></p></div>
                </div>
            </div>
        </div>

    </div>
    <div class="row card-row-mobile">
        <div class="col-12 col-lg-4 card-col">
            <div>
                <h2>The Nevermore Haunt</h2>
                <div>
                    <div><%= image_tag("patient-attractions.jpg") %>
                    </div>
                </div>
            </div>
            <div class="card-mobile-caption">
                <p><%= phrase('attractions-nevermore-description') %></p>
            </div>
        </div>
        <div class="col-12 col-lg-4 card-col">
            <div>
                <h2>Isaac's Maleficent Side Show</h2>
                <div>
                    <div><%= image_tag("pajama-man-attractions.jpg") %></div>
                </div>
            </div>
            <div class="card-mobile-caption">
                <p><%= phrase('attractions-sideshow-description') %></p>
            </div>
        </div>
        <div class="col-12 col-lg-4 card-col">
            <div>
                <h2>Food &amp; Drink</h2>
                <div>
                    <div><%= image_tag("hot-dogs.jpg") %></div>
                </div>
            </div>
            <div class="card-mobile-caption">
                <p><%= phrase('attractions-food-drink-description') %></p>
            </div>
        </div>

    </div>
    <div class="attractions-ie-wrap">
        <div class="row card-row-ie">
            <div class="col-12 col-lg-4 card-col">
                <div>
                    <h2>The Nevermore Haunt</h2>
                    <div>
                        <div><%= image_tag("patient-attractions.jpg") %>
                        </div>
                    </div>
                </div>
                <div class="card-mobile-caption">
                    <p><%= phrase('attractions-nevermore-description') %></p>
                </div>
            </div>
            <div class="col-12 col-lg-4 card-col">
                <div>
                    <h2>Isaac's Maleficent Side Show</h2>
                    <div>
                        <div><%= image_tag("pajama-man-attractions.jpg") %></div>
                    </div>
                </div>
                <div class="card-mobile-caption">
                    <p><%= phrase('attractions-sideshow-description') %></p>
                </div>
            </div>
            <div class="col-12 col-lg-4 card-col">
                <div>
                    <h2>Food &amp; Drink</h2>
                    <div>
                        <div><%= image_tag("hot-dogs.jpg") %></div>
                    </div>
                </div>
                <div class="card-mobile-caption">
                    <p><%= phrase('attractions-food-drink-description') %></p>
                </div>
            </div>

        </div>
    </div>
</div>


<div class="container-fluid warning">
    <h1>Warning</h1>
    <h2><%= phrase('warning-body') %></h2>
</div>
<br><br>
<br><br>

    <div class="container seo-blurb">
        <h1>Baltimore, Maryland's Scariest Haunted House</h1>
        <h2><%= phrase('home-page-blurb-1-heading') %></h2>
        <p><%= phrase('home-page-blurb-1-body') %></p>
        <br><br>
        <h2><%= phrase('home-page-blurb-2-heading') %></h2>
        <p><%= phrase('home-page-blurb-2-body') %></p>
        <br><br>
        <h2><%= phrase('home-page-blurb-3-heading') %></h2>
        <p><%= phrase('home-page-blurb-3-body') %></p>
    </div>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>